### ISSUE TITLE
Kiosk View

### ISSUE THREAD

**Issue by mdavidlawson** [mdavidlawson/mayofest-member-api#1]
Create the GUI for the checkin kiosk. 

The view must:
  * Be built using twitter bootstrap componants
  * Minimal custom CSS
  * Minimal custom html to place (use grid system offered by bootstrap)
  * Be somewhat accessible
    * Large, easy to read font with tab support
    * Descriptions where absolutly necissary
    * tooltips where absolutly necissary 

The checkin kiosk must:
  * Capture all information from a new member. All information is defined as the questions asked on this form: https://docs.google.com/a/mayofest.org/forms/d/1T2_BNQ66X8vyzC3ZQEYI5-Vp38KvYNlsEYRfjVC_-eM/edit with the following additional information
    - Marketing information (to be confirmed by Marketing Section Leader)
    - Questionarre info (to be confirmed by Mayo)

**Comment by jemtoo** [comment]
Can we add licence plate info?

**Comment by mdavidlawson** [comment]
I'll run this by Ema... it's a good idea but I don't know that it makes sense for it to exist in the system only to be immediatly confirmed by tuckshop. We wouldn't be building in anything that uses that info this year either.
